# Generated by Django 5.2.4 on 2025-08-13 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
