# Generated by Django 5.2.4 on 2025-08-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dues',
            options={},
        ),
        migrations.AddField(
            model_name='dues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dues',
            name='receipt_number',
            field=models.CharField(blank=True, default=99, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
