# Generated by Django 5.2.4 on 2025-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('home_town', models.CharField(blank=True, max_length=30)),
                ('house_number', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, choices=[(None, 'Select Region'), ('GA', 'Greater Accra'), ('AR', 'Ashante Region'), ('CR', 'Central Region'), ('WR', 'Western Region'), ('WN', 'Western North'), ('ER', 'Eastern Region'), ('VR', 'Volta Region'), ('BA', 'Ahafo Region'), ('BE', 'Bono East'), ('BR', 'Bono Region'), ('NR', 'Northern Region'), ('NE', 'North East'), ('SR', 'Savannah Region'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('OR', 'Oti Region')], max_length=2)),
                ('gender', models.CharField(blank=True, choices=[(None, 'Select Gender'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(blank=True, choices=[(None, 'Marital Status'), ('M', 'Married'), ('S', 'Single'), ('D', 'Divorced')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, choices=[(None, 'Select Category'), ('chairperson', 'chairperson'), ('secretary', 'secretary'), ('finance', 'finance'), ('tresurer', 'tresurer'), ('member', 'member')], max_length=15)),
                ('staff_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
