# Generated by Django 5.2.4 on 2025-08-08 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gender_maritalstatus_region_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='serial_number',
        ),
    ]
