# Generated by Django 5.2.4 on 2025-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'empty'), ('chairperson', 'chairperson'), ('secretary', 'secretary'), ('finance', 'finance'), ('tresurer', 'tresurer'), ('member', 'member')], default='member', max_length=15),
        ),
    ]
