# Generated by Django 5.2.4 on 2025-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='MaritalStatus',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[(None, ''), ('chairperson', 'chairperson'), ('secretary', 'secretary'), ('finance', 'finance'), ('tresurer', 'tresurer'), ('member', 'member')], max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select Gender'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[(None, 'Marital Status'), ('M', 'Married'), ('S', 'Single'), ('D', 'Divorced')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, choices=[(None, 'Select Region'), ('GA', 'Greater Accra'), ('AR', 'Ashante Region'), ('CR', 'Central Region'), ('WR', 'Western Region'), ('WN', 'Western North'), ('ER', 'Eastern Region'), ('VR', 'Volta Region'), ('BA', 'Ahafo Region'), ('BE', 'Bono East'), ('BR', 'Bono Region'), ('NR', 'Northern Region'), ('NE', 'North East'), ('SR', 'Savannah Region'), ('UE', 'Upper East'), ('UW', 'Upper West'), ('OR', 'Oti Region')], max_length=2),
        ),
    ]
