# Generated by Django 5.2.4 on 2025-08-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_category_delete_gender_delete_maritalstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[(None, 'Select Category'), ('chairperson', 'chairperson'), ('secretary', 'secretary'), ('finance', 'finance'), ('tresurer', 'tresurer'), ('member', 'member')], max_length=15),
        ),
    ]
