# Generated by Django 5.2.4 on 2025-08-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(blank=True, max_length=30, null=True)),
                ('detail', models.CharField(blank=True, max_length=150, null=True)),
                ('supporting_document', models.FileField(upload_to='supporting_documents')),
                ('member', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
