# Generated by Django 5.2.4 on 2025-08-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='honoured',
            field=models.BooleanField(default=False),
        ),
    ]
