# Generated by Django 5.2.4 on 2025-08-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenefitType',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('Marriage', 'Marriage'), ('Accident', 'Accident'), ('Ill-health', 'Ill-health'), (None, 'Select Benefit'), ('Funeral', 'Funeral'), ('Birth', 'Birth')], max_length=30, null=True),
        ),
    ]
