# Generated by Django 5.2.4 on 2025-08-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_benefit_honoured'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount to be paid for this benefit.', max_digits=10, null=True),
        ),
    ]
