# Generated by Django 5.2.4 on 2025-08-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_benefit_benefit_type_children_nextofkin_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('Birth', 'Birth'), ('Marriage', 'Marriage'), ('Ill-health', 'Ill-health'), (None, 'Select Benefit'), ('Funeral', 'Funeral'), ('Accident', 'Accident')], max_length=30, null=True),
        ),
    ]
