# Generated by Django 5.2.4 on 2025-08-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_benefit_benefit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('Ill-health', 'Ill-health'), ('Marriage', 'Marriage'), ('Accident', 'Accident'), (None, 'Select Benefit'), ('Funeral', 'Funeral'), ('Birth', 'Birth')], max_length=30, null=True),
        ),
    ]
