# Generated by Django 5.2.4 on 2025-08-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_benefit_benefit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('Marriage', 'Marriage'), ('Funeral', 'Funeral'), ('Birth', 'Birth'), ('Accident', 'Accident'), ('Ill-health', 'Ill-health'), (None, 'Select Benefit')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='supporting_document',
            field=models.FileField(blank=True, null=True, upload_to='supporting_documents'),
        ),
    ]
