# Generated by Django 5.2.4 on 2025-08-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_benefit_benefit_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benefit',
            name='member',
        ),
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('Ill-health', 'Ill-health'), ('Accident', 'Accident'), ('Marriage', 'Marriage'), ('Birth', 'Birth'), ('Funeral', 'Funeral'), (None, 'Select Benefit')], max_length=30, null=True),
        ),
    ]
