# Generated by Django 5.2.4 on 2025-08-09 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_benefit_member_alter_benefit_benefit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[(None, 'Select Benefit'), ('Birth', 'Birth'), ('Accident', 'Accident'), ('Funeral', 'Funeral'), ('Marriage', 'Marriage'), ('Ill-health', 'Ill-health')], max_length=30, null=True),
        ),
    ]
