# Generated by Django 5.2.4 on 2025-08-10 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_benefit_member_alter_benefit_benefit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Benefit', 'verbose_name_plural': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='children',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='nextofkin',
            options={'verbose_name': 'Next of Kin', 'verbose_name_plural': 'Next of Kin'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='spouse',
            options={'verbose_name': 'Spouse', 'verbose_name_plural': 'Spouses'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('Marriage', 'Marriage'), ('Birth', 'Birth'), ('Funeral', 'Funeral'), ('Accident', 'Accident'), ('Ill-health', 'Ill-health')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='fathers_first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Father's First Name"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='fathers_last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Father's Last Name"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='fathers_middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Father's Middle Name"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mothers_first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Mother's First Name"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mothers_last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Mother's Last Name"),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mothers_middle_name',
            field=models.CharField(blank=True, max_length=30, verbose_name="Mother's Middle Name"),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
